### ISSUE TITLE
Examples folder missing

### ISSUE THREAD

**Issue by murkle** [carlos-menezes/libg203lightsync#1]
https://github.com/carlos-menezes/libg203lightsync/blob/master/examples (referenced from https://github.com/carlos-menezes/libg203lightsync/blob/master/README.md ) gives 404

**Comment by carlos-menezes** [comment]
I removed that folder while tidying up the Makefile. The folder was added re-added (with better examples) in 35e07a4cb8e76771dc96dea04aff53123bd38085. Thank you!

**Comment by murkle** [comment]
Thanks :)
