### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by murkle** [carlos-menezes/libg203lightsync#2]
Do you have a link for the protocol info? Just thinking maybe it could work using WebHID maybe which would be very cool

**Comment by carlos-menezes** [comment]
Unfortunately I didn't find any information on the protocol, I simply resorted to sending commands from the G Hub software to the mouse and checking out the bytes sent via Wireshark. Might be worth it documenting the protocol in a separate file now that you talk about.

Regardless, if you take a look at `libg203lightsync.cpp` (more specifically, at the implementations of the commands like `set_solid_color`), you should be able replicate the behaviour of this library!

**Comment by murkle** [comment]
Is it using the HID protocol to send the info?

**Comment by carlos-menezes** [comment]
This library uses `libusb` but not the `hidapi`.
